# Generated by Django 2.2.3 on 2019-07-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('current_position_x', models.FloatField(blank=True, null=True)),
                ('current_position_y', models.FloatField(blank=True, null=True)),
                ('current_velocity', models.FloatField(blank=True, null=True)),
                ('tire_pressure_left_front', models.FloatField(blank=True, null=True)),
                ('tire_pressure_right_front', models.FloatField(blank=True, null=True)),
                ('tire_pressure_left_behind', models.FloatField(blank=True, null=True)),
                ('tire_pressure_right_behind', models.FloatField(blank=True, null=True)),
                ('camera_status', models.NullBooleanField()),
                ('lidar_status', models.NullBooleanField()),
                ('ibeo_status', models.NullBooleanField()),
                ('car_status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('a', 'Available'), ('r', 'Running')], default='m', max_length=1)),
                ('route', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('login_or_create', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('start_position_x', models.FloatField(blank=True, null=True)),
                ('start_position_y', models.FloatField(blank=True, null=True)),
                ('target_position_x', models.FloatField(blank=True, null=True)),
                ('target_position_y', models.FloatField(blank=True, null=True)),
                ('is_car_arrive_start', models.NullBooleanField()),
                ('is_in_car', models.NullBooleanField()),
                ('is_car_reach_target', models.NullBooleanField()),
                ('is_car_start_to_start_point', models.NullBooleanField()),
                ('order_status', models.CharField(blank=True, choices=[('p', 'Preparing'), ('f', 'Finished'), ('r', 'Running')], default='p', max_length=1)),
                ('order_creation_time', models.TimeField()),
                ('order_end_time', models.TimeField(blank=True, null=True)),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxitest.Car')),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxitest.Client')),
            ],
            options={
                'ordering': ['order_creation_time'],
            },
        ),
    ]
