# Generated by Django 2.2.3 on 2019-07-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_creation_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
