# Generated by Django 2.2.3 on 2019-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxitest', '0002_auto_20190713_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
